---
- name: adminer
  src: https://github.com/alexandrubau/ansible-adminer.git
- name: apache
  src: https://github.com/alexandrubau/ansible-apache.git
- name: certbot
  src: https://github.com/alexandrubau/ansible-certbot.git
- name: deploy
  src: https://github.com/alexandrubau/ansible-deploy.git
- name: mysql
  src: https://github.com/alexandrubau/ansible-mysql.git
- name: nginx
  src: https://github.com/alexandrubau/ansible-nginx.git
- name: nodejs
  src: https://github.com/alexandrubau/ansible-nodejs.git
- name: php
  src: https://github.com/alexandrubau/ansible-php.git
- name: redis
  src: https://github.com/alexandrubau/ansible-redis.git
- name: samba
  src: https://github.com/alexandrubau/ansible-samba.git
- name: security
  src: https://github.com/alexandrubau/ansible-security.git