# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.define "athena" do |athena|
        athena.vm.box       = "bento/ubuntu-18.04"
        athena.vm.hostname  = "athena.local"
        athena.vm.network "private_network", ip: "192.168.13.37"
        athena.vm.synced_folder "../", "/vagrant"
    end

    config.vm.provider "virtualbox" do |vbox|
        vbox.memory = 512
        vbox.cpus   = 1
    end

    config.vm.provision "file", source: "~/.ssh/id_rsa", destination: "/home/vagrant/.ssh/id_rsa"

    config.vm.provision "shell", path: "Vagrantboot"

    config.vm.provision "ansible_local" do |ansible|
        ansible.inventory_path    = "auto/inventories/dev/hosts"
        ansible.playbook          = "auto/provision.yml"
        ansible.limit             = "all"
    end

    config.vm.provision "ansible_local" do |ansible|
        ansible.inventory_path    = "auto/inventories/dev/hosts"
        ansible.playbook          = "auto/deploy.yml"
        ansible.limit             = "all"
    end
end
